In [1]:
import pandas as pd
df=pd.read_csv("updated_pollution_dataset.csv")
df


Temperature  Humidity  PM2.5   PM10   NO2   SO2    CO  \
0            29.8      59.1    5.2   17.9  18.9   9.2  1.72   
1            28.3      75.6    2.3   12.2  30.8   9.7  1.64   
2            23.1      74.7   26.7   33.8  24.4  12.6  1.63   
3            27.1      39.1    6.1    6.3  13.5   5.3  1.15   
4            26.5      70.7    6.9   16.0  21.9   5.6  1.01   
...           ...       ...    ...    ...   ...   ...   ...   
4995         40.6      74.1  116.0  126.7  45.5  25.7  2.11   
4996         28.1      96.9    6.9   25.0  25.3  10.8  1.54   
4997         25.9      78.2   14.2   22.1  34.8   7.8  1.63   
4998         25.3      44.4   21.4   29.0  23.7   5.7  0.89   
4999         24.1      77.9   81.7   94.3  23.2  10.5  1.38   

      Proximity_to_Industrial_Areas  Population_Density Air Quality  
0                               6.3                 319    Moderate  
1                               6.0                 611    Moderate  
2                               5.2                 619    Moderate  
3                              11.1                 551        Good  
4                              12.7                 303        Good  
...                             ...                 ...         ...  
4995                            2.8                 765   Hazardous  
4996                            5.7                 709    Moderate  
4997                            9.6                 379    Moderate  
4998                           11.6                 241        Good  
4999                            8.3                 461    Moderate  

[5000 rows x 10 columns]

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Temperature                    5000 non-null   float64
 1   Humidity                       5000 non-null   float64
 2   PM2.5                          5000 non-null   float64
 3   PM10                           5000 non-null   float64
 4   NO2                            5000 non-null   float64
 5   SO2                            5000 non-null   float64
 6   CO                             5000 non-null   float64
 7   Proximity_to_Industrial_Areas  5000 non-null   float64
 8   Population_Density             5000 non-null   int64  
 9   Air Quality                    5000 non-null   object 
dtypes: float64(8), int64(1), object(1)
memory usage: 390.8+ KB


In [3]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Air Quality']=le.fit_transform(df['Air Quality'])


In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Temperature                    5000 non-null   float64
 1   Humidity                       5000 non-null   float64
 2   PM2.5                          5000 non-null   float64
 3   PM10                           5000 non-null   float64
 4   NO2                            5000 non-null   float64
 5   SO2                            5000 non-null   float64
 6   CO                             5000 non-null   float64
 7   Proximity_to_Industrial_Areas  5000 non-null   float64
 8   Population_Density             5000 non-null   int64  
 9   Air Quality                    5000 non-null   int64  
dtypes: float64(8), int64(2)
memory usage: 390.8 KB


In [5]:
df.isnull()

Temperature  Humidity  PM2.5   PM10    NO2    SO2     CO  \
0           False     False  False  False  False  False  False   
1           False     False  False  False  False  False  False   
2           False     False  False  False  False  False  False   
3           False     False  False  False  False  False  False   
4           False     False  False  False  False  False  False   
...           ...       ...    ...    ...    ...    ...    ...   
4995        False     False  False  False  False  False  False   
4996        False     False  False  False  False  False  False   
4997        False     False  False  False  False  False  False   
4998        False     False  False  False  False  False  False   
4999        False     False  False  False  False  False  False   

      Proximity_to_Industrial_Areas  Population_Density  Air Quality  
0                             False               False        False  
1                             False               False        False  
2                             False               False        False  
3                             False               False        False  
4                             False               False        False  
...                             ...                 ...          ...  
4995                          False               False        False  
4996                          False               False        False  
4997                          False               False        False  
4998                          False               False        False  
4999                          False               False        False  

[5000 rows x 10 columns]

In [6]:
df.isnull().sum()

Temperature                      0
Humidity                         0
PM2.5                            0
PM10                             0
NO2                              0
SO2                              0
CO                               0
Proximity_to_Industrial_Areas    0
Population_Density               0
Air Quality                      0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [9]:
a=df.drop(['Air Quality'],axis=1)
b=df['Air Quality']
print(a)
print(b)

      Temperature  Humidity  PM2.5   PM10   NO2   SO2    CO  \
0            29.8      59.1    5.2   17.9  18.9   9.2  1.72   
1            28.3      75.6    2.3   12.2  30.8   9.7  1.64   
2            23.1      74.7   26.7   33.8  24.4  12.6  1.63   
3            27.1      39.1    6.1    6.3  13.5   5.3  1.15   
4            26.5      70.7    6.9   16.0  21.9   5.6  1.01   
...           ...       ...    ...    ...   ...   ...   ...   
4995         40.6      74.1  116.0  126.7  45.5  25.7  2.11   
4996         28.1      96.9    6.9   25.0  25.3  10.8  1.54   
4997         25.9      78.2   14.2   22.1  34.8   7.8  1.63   
4998         25.3      44.4   21.4   29.0  23.7   5.7  0.89   
4999         24.1      77.9   81.7   94.3  23.2  10.5  1.38   

      Proximity_to_Industrial_Areas  Population_Density  
0                               6.3                 319  
1                               6.0                 611  
2                               5.2                 619  
3          

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
T=sc.fit_transform(a)
print(T)

[[-0.03408041 -0.69071534 -0.60858932 ...  0.40230264 -0.58865846
  -1.16816284]
 [-0.25729505  0.34950721 -0.72670554 ...  0.25577499 -0.67174754
   0.74359753]
 [-1.03110581  0.2927678   0.26709986 ...  0.23745904 -0.89331843
   0.79597453]
 ...
 [-0.61443848  0.51342107 -0.24202176 ...  0.23745904  0.32532146
  -0.77533537]
 [-0.70372434 -1.61745907  0.0512323  ... -1.11792167  0.87924868
  -1.67883856]
 [-0.88229605  0.49450793  2.50723499 ... -0.22043985 -0.03473124
  -0.23847116]]


In [11]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
a_train,a_test,b_train,b_test=train_test_split(a,b,test_size=0.2,random_state=25)
model=LogisticRegression()
model.fit(a_train,b_train)
b_pred=model.predict(a_test)
print(b_pred)

[0 0 0 0 0 1 0 2 1 0 0 0 0 3 2 3 2 0 2 2 3 2 0 2 3 3 2 2 1 2 3 2 3 3 0 0 1
 3 3 0 3 0 2 0 0 3 0 0 0 1 1 2 3 0 0 0 2 0 3 0 3 3 3 2 0 0 0 0 2 0 0 1 0 0
 1 0 3 0 0 0 0 2 2 2 0 0 0 0 0 2 3 2 1 3 2 2 0 3 3 2 3 0 0 2 2 0 2 0 2 2 3
 2 2 2 2 2 3 0 2 0 2 0 0 0 2 2 1 2 3 0 2 0 0 0 0 0 3 3 0 3 2 2 3 0 0 0 2 3
 0 1 0 2 2 1 0 0 0 0 2 0 2 2 0 0 3 2 2 0 0 0 2 2 2 0 2 0 0 0 0 3 0 0 2 0 2
 3 1 3 3 0 1 2 1 3 2 0 0 0 2 2 3 2 0 2 0 3 0 0 0 0 0 1 2 2 0 2 0 0 2 0 0 2
 1 0 2 0 0 0 0 0 2 1 2 0 2 0 0 0 3 2 2 0 2 3 0 3 0 1 2 0 0 0 0 0 3 2 0 0 2
 2 0 2 2 2 1 2 0 0 3 0 2 0 2 2 3 3 0 3 1 0 3 0 2 2 0 0 0 0 0 3 0 3 0 2 0 0
 2 0 0 0 2 1 2 2 0 2 0 2 0 0 0 2 3 3 2 3 1 0 0 3 0 3 2 0 2 0 0 2 2 0 2 2 0
 2 2 2 2 0 0 0 3 0 3 2 2 0 2 3 0 1 2 0 2 1 3 2 0 3 0 3 2 0 0 0 2 2 0 0 2 0
 2 1 3 0 3 2 0 3 1 1 0 2 1 1 0 0 0 2 2 1 2 0 0 2 0 0 2 3 0 0 2 0 1 3 0 0 2
 2 0 2 1 3 2 2 2 0 0 0 0 0 2 3 0 2 2 0 0 2 1 0 2 0 2 3 0 0 3 0 3 0 2 0 1 0
 3 0 2 0 0 0 2 3 2 3 2 2 3 0 3 0 2 3 2 0 0 0 3 3 0 2 2 2 2 0 0 0 2 2 0 0 2
 1 2 2 2 0 0 3 2 0 2 2 3 

c:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [12]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(b_test,b_pred))
print(confusion_matrix(b_test,b_pred))
print(classification_report(b_test,b_pred))



0.746
[[400   0   3   0]
 [  0  32  14  53]
 [ 27   5 233  44]
 [  3  29  76  81]]
              precision    recall  f1-score   support

           0       0.93      0.99      0.96       403
           1       0.48      0.32      0.39        99
           2       0.71      0.75      0.73       309
           3       0.46      0.43      0.44       189

    accuracy                           0.75      1000
   macro avg       0.65      0.62      0.63      1000
weighted avg       0.73      0.75      0.74      1000



In [13]:
model=LogisticRegression()
model.fit(a_test,b_test)
b_pred=model.predict(a_test)

c:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [14]:
print(accuracy_score(b_test,b_pred))
print(confusion_matrix(b_test,b_pred))
print(classification_report(b_test,b_pred))

0.758
[[390   0  13   0]
 [  0  38   9  52]
 [ 19   8 229  53]
 [  2  25  61 101]]
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       403
           1       0.54      0.38      0.45        99
           2       0.73      0.74      0.74       309
           3       0.49      0.53      0.51       189

    accuracy                           0.76      1000
   macro avg       0.68      0.66      0.66      1000
weighted avg       0.75      0.76      0.75      1000

